"""Tablas de códigos de Aduana para los documentos de exportación.

El Formato DTE del SII no define estos códigos: remite a **www.aduana.cl**. Están
extraídos del Compendio de Normas Aduaneras, Anexo 51, y son los que llenan el
bloque <Aduana> de la factura de exportación.

Los nombres van sin tildes, como los publica el Compendio. Para buscar sin
depender de acentos ni mayúsculas, usar :func:.

Fuente: https://www.aduana.cl/compendio-de-normas-anexo-51/aduana/2009-11-19/163937.html
"""

# Los nombres largos vienen tal cual del Compendio: no se recortan para que
# calcen con lo que el contribuyente ve en la documentacion de Aduana.
# ruff: noqa: E501
from __future__ import annotations

import unicodedata

# Paises (Anexo 51-9)
COUNTRIES: dict[str, int] = {
    "SENEGAL": 101,
    "GAMBIA": 102,
    "GUINEA - BISSAU": 103,
    "GUINEA": 104,
    "SIERRA LEONA": 105,
    "LIBERIA": 106,
    "COSTA DE MARFIL": 107,
    "GHANA": 108,
    "TOGO": 109,
    "NIGERIA": 111,
    "SUDAFRICA": 112,
    "BOTSWANA": 113,
    "LESOTHO": 114,
    "MALAWI": 115,
    "ZIMBABWE": 116,
    "ZAMBIA": 117,
    "COMORAS": 118,
    "MAURICIO": 119,
    "MADAGASCAR": 120,
    "MOZAMBIQUE": 121,
    "SWAZILANDIA": 122,
    "SUDAN": 123,
    "EGIPTO": 124,
    "LIBIA": 125,
    "TUNEZ": 126,
    "ARGELIA": 127,
    "MARRUECOS": 128,
    "CABO VERDE": 129,
    "CHAD": 130,
    "NIGER": 131,
    "MALI": 133,
    "MAURITANIA": 134,
    "TANZANIA": 135,
    "UGANDA": 136,
    "KENIA": 137,
    "SOMALIA": 138,
    "ETIOPIA": 139,
    "ANGOLA": 140,
    "BURUNDI": 141,
    "RWANDA": 142,
    "REPUBLICA DEMOCRATICA DEL CONGO": 143,
    "CONGO": 144,
    "GABON": 145,
    "CAMERUN": 149,
    "BENIN": 150,
    "TERRITORIO BRITANICO EN AFRICA": 151,
    "TERRITORIO ESPANOL EN AFRICA": 152,
    "TERRITORIO FRANCES EN AFRICA": 153,
    "DJIBOUTI": 155,
    "SEYCHELLES": 156,
    "NAMIBIA": 159,
    "BURKINA FASO": 161,
    "ERITREA": 163,
    "ISLAS MARSHALL": 164,
    "SAHARA OCCIDENTAL": 165,
    "VENEZUELA": 201,
    "COLOMBIA": 202,
    "BARBADOS": 204,
    "JAMAICA": 205,
    "BAHAMAS": 207,
    "HAITI": 208,
    "CUBA": 209,
    "PANAMA": 210,
    "COSTA RICA": 211,
    "NICARAGUA": 212,
    "EL SALVADOR": 213,
    "HONDURAS": 214,
    "GUATEMALA": 215,
    "MEXICO": 216,
    "GUYANA": 217,
    "ECUADOR": 218,
    "PERU": 219,
    "BRASIL": 220,
    "BOLIVIA": 221,
    "PARAGUAY": 222,
    "URUGUAY": 223,
    "ARGENTINA": 224,
    "CANADA": 226,
    "TERRITORIO BRITANICO EN AMERICA": 227,
    "TERRITORIO FRANCES EN AMERICA": 228,
    "TERRITORIO HOLANDES EN AMERICA": 229,
    "TERRITORIO DE DINAMARCA": 230,
    "DOMINICA": 231,
    "GRANADA": 232,
    "SANTA LUCIA (ISLAS OCCIDENTALES)": 233,
    "SURINAM": 235,
    "BELICE": 236,
    "ANGUILA": 242,
    "ARUBA": 243,
    "BERMUDAS": 244,
    "ISLAS VIRGENES BRITANICAS": 245,
    "ISLAS CAYMAN": 246,
    "ANTILLAS NEERLANDESAS": 247,
    "TURCAS Y CAICOS": 248,
    "ISLAS VIRGENES (ESTADOS UNIDOS DE AMERICA)": 249,
    "MARTINICA": 250,
    "PUERTO RICO": 251,
    "MONSERRAT": 252,
    "GROENLANDIA": 253,
    "JORDANIA": 301,
    "ARABIA SAUDITA": 302,
    "KUWAIT": 303,
    "OMAN": 304,
    "CHIPRE": 305,
    "ISRAEL": 306,
    "IRAK": 307,
    "AFGHANISTAN": 308,
    "IRAN": 309,
    "SIRIA": 310,
    "LIBANO": 311,
    "QATAR": 312,
    "BAHREIN": 313,
    "SRI LANKA": 314,
    "CAMBODIA": 315,
    "LAOS": 316,
    "INDIA": 317,
    "BUTAN": 318,
    "THAILANDIA": 319,
    "NEPAL": 320,
    "BANGLADESH": 321,
    "PAKISTAN": 324,
    "VIETNAM": 325,
    "MYANMAR (EX BIRMANIA)": 326,
    "ISLAS MALDIVAS": 327,
    "INDONESIA": 328,
    "MALASIA": 329,
    "TAIWAN (FORMOSA)": 330,
    "JAPON": 331,
    "SINGAPUR": 332,
    "COREA DEL SUR": 333,
    "COREA DEL NORTE": 334,
    "FILIPINAS": 335,
    "CHINA": 336,
    "MONGOLIA": 337,
    "TERRITORIO PORTUGUES EN ASIA": 343,
    "BRUNEI": 344,
    "MACAO": 345,
    "REPUBLICA DE YEMEN": 346,
    "FIJI": 401,
    "NAURU": 402,
    "ISLAS TONGA": 403,
    "NUEVA ZELANDIA": 405,
    "AUSTRALIA": 406,
    "TERRITORIO BRITANICO EN OCEANIA Y EL PACIFICO": 407,
    "TERRITORIO FRANCES EN OCEANIA Y EL PACIFICO": 408,
    "TERRITORIO NORTEAMERICANO EN OCEANIA Y EL PACIFICO": 409,
    "VANUATU": 415,
    "KIRIBATI": 416,
    "MICRONESIA": 417,
    "ISLAS SALOMON": 418,
    "TUVALU": 419,
    "BELAU": 420,
    "NIUE": 421,
    "POLINESIA FRANCESA": 422,
    "NUEVA CALEDONIA": 423,
    "ISLAS MARIANAS DEL NORTE": 424,
    "GUAM": 425,
    "TIMOR ORIENTAL": 426,
    "ISLAS COOK": 427,
    "PORTUGAL": 501,
    "ITALIA": 504,
    "FRANCIA": 505,
    "IRLANDA": 506,
    "DINAMARCA": 507,
    "SUIZA": 508,
    "AUSTRIA": 509,
    "REINO UNIDO": 510,
    "SUECIA": 511,
    "FINLANDIA": 512,
    "NORUEGA": 513,
    "BELGICA": 514,
    "PAISES BAJOS": 515,
    "ISLANDIA": 516,
    "ESPANA": 517,
    "ALBANIA": 518,
    "RUMANIA": 519,
    "GRECIA": 520,
    "TURQUIA": 522,
    "MALTA": 523,
    "SANTA SEDE": 524,
    "ANDORRA": 525,
    "BULGARIA": 527,
    "POLONIA": 528,
    "HUNGRIA": 530,
    "LUXEMBURGO": 532,
    "LIECHTENSTEIN": 534,
    "MONACO": 535,
    "SAN MARINO": 536,
    "ARMENIA": 540,
    "AZERBAIJAN": 541,
    "BELARUS": 542,
    "REPUBLICA CHECA (D)": 544,
    "CROACIA": 547,
    "ESLOVENIA": 548,
    "ESTONIA": 549,
    "GEORGIA": 550,
    "KASAJSTAN": 551,
    "KIRGISTAN": 552,
    "LETONIA": 553,
    "LITUANIA": 554,
    "MACEDONIA": 555,
    "MOLDOVA": 556,
    "TADJIKISTAN": 557,
    "TURKMENISTAN": 558,
    "UCRANIA": 559,
    "UZBEKISTAN": 560,
    "RUSIA (B)": 562,
    "ALEMANIA": 563,
    "GIBRALTAR": 565,
    "GUERNSEY": 566,
    "ISLAS DE MAN": 567,
    "JERSEY": 568,
    "Combustibles y lubricantes destinados al consumo de naves y aeronaves extranjeras y de revistas con el mismo objeto": 901,
    'Aprovisionamiento ("Rancho") de naves y aeronaves extranjeras y de maderas para estibar mercancias cargadas en puertos chilenos': 902,
    "Rancho de Naves y Aeronaves Extranjeras y de maderas para estibar mercancias cargadas en puertos chilenos": 902,
    "Origenes o Destinaciones no precisadas por razones comerciales o militares": 904,
    "Deposito Franco": 906,
    "CHILE": 997,
    "Otros (Pais Desconocido)": 999,
}

# Puertos (Anexo 51-11)
PORTS: dict[str, int] = {
    "MONTREAL": 111,
    "HALIFAX": 113,
    "VANCOUVER": 114,
    "SAINT JOHN": 115,
    "TORONTO": 116,
    "OTROS PUERTOS DE CANADA NO IDENTIFICADOS": 117,
    "BAYSIDE": 118,
    "PORT CARTIES": 120,
    "COSTA DEL ATLANTICO, OTROS NO ESPECIFICADOS COMPRENDIDOS ENTRE MAINE Y KEY WEST": 121,
    "PUERTOS DEL GOLFO DE MEXICO, OTROS NO ESPECIFICADOS COMPRENDIDOS ENTRE KEY WEST Y BROWNSVILLE": 122,
    "COSTA DEL PACIFICO, OTROS NO ESPECIFICADOS": 123,
    "QUEBEC": 124,
    "PRINCE RUPERT": 125,
    "HAMILTON": 126,
    "BOSTON": 131,
    "NEW HAVEN": 132,
    "BRIDGEPORT": 133,
    "NEW YORK": 134,
    "FILADELFIA": 135,
    "BALTIMORE": 136,
    "NORFOLK": 137,
    "CHARLESTON": 139,
    "SAVANAH": 140,
    "MIAMI": 141,
    "EVERGLADES": 142,
    "JACKSONVILLE": 143,
    "PALM BEACH": 145,
    "BATON ROUGE": 146,
    "COLUMBRES": 147,
    "PITTSBURGH": 148,
    "DULUTH": 149,
    "MILWAUKEE": 150,
    "TAMPA": 151,
    "PENSACOLA": 152,
    "MOBILE": 153,
    "NEW ORLEANS": 154,
    "PORT ARTHUR": 155,
    "GALVESTON": 156,
    "CORPUS CRISTI": 157,
    "BROWNSVILLE": 158,
    "HOUSTON": 159,
    "OAKLAND": 160,
    "STOCKTON": 161,
    "SEATTLE": 171,
    "PORTLAND": 172,
    "LOS ANGELES": 174,
    "LONG BEACH": 175,
    "SAN DIEGO": 176,
    "OTROS PUERTOS DE ESTADOS UNIDOS NO ESPECIFICADOS": 180,
    "PUNTA CHUNGO": 190,
    "LOS VILOS": 199,
    "PATACHE": 204,
    "CALBUCO": 205,
    "MICHILLA": 206,
    "PUERTO ANGAMOS": 207,
    "POSEIDON": 208,
    "TRES PUENTES": 209,
    "OTROS PUERTOS DE MEXICO NO ESPECIFICADOS": 210,
    "TAMPICO": 211,
    "COSTA DEL PACIFICO, OTROS PUERTOS": 212,
    "VERACRUZ": 213,
    "COATZACOALCOS": 214,
    "GUAYMAS": 215,
    "MAZATLAN": 216,
    "MANZANILLO": 217,
    "ACAPULCO": 218,
    "GOLFO DE MEXICO, OTROS NO ESPECIFICADOS": 219,
    "ALTAMIRA": 220,
    "CRISTOBAL": 221,
    "BALBOA": 222,
    "COLON": 223,
    "OTROS PUERTOS DE PANAMA NO ESPECIFICADOS": 224,
    "PASO GUANACO SONSO": 225,
    "OTROS PUERTOS DE COLOMBIA NO ESPECIFICADOS": 231,
    "BUENAVENTURA": 232,
    "BARRANQUILLA": 233,
    "OTROS PUERTOS DE ECUADOR NO ESPECIFICADOS": 241,
    "GUAYAQUIL": 242,
    "OTROS PUERTOS DE PERU NO ESPECIFICADOS": 251,
    "CALLAO": 252,
    "ILO": 253,
    "IQUITOS": 254,
    "OTROS PUERTOS DE ARGENTINA NO ESPECIFICADOS": 261,
    "BUENOS AIRES": 262,
    "NECOCHEA": 263,
    "MENDOZA": 264,
    "CORDOBA": 265,
    "BAHIA BLANCA": 266,
    "COMODORO RIVADAVIA": 267,
    "PUERTO MADRYN": 268,
    "MAR DEL PLATA": 269,
    "ROSARIO": 270,
    "OTROS PUERTOS DE URUGUAY NO ESPECIFICADOS": 271,
    "MONTEVIDEO": 272,
    "OTROS PUERTOS DE VENEZUELA NO ESPECIFICADOS": 281,
    "LA GUAIRA": 282,
    "MARACAIBO": 285,
    "OTROS PUERTOS DE BRASIL NO ESPECIFICADOS": 291,
    "SANTOS": 292,
    "RIO DE JANEIRO": 293,
    "RIO GRANDE DEL SUR": 294,
    "PARANAGUA": 295,
    "SAO PAULO": 296,
    "SALVADOR": 297,
    "OTROS PUERTOS DE LAS ANTILLAS HOLANDESAS NO ESPECIFICADOS": 301,
    "CURAZAO": 302,
    "OTROS PUERTOS DE AMERICA NO ESPECIFICADOS": 399,
    "SHANGAI": 411,
    "DAIREN": 412,
    "OTROS PUERTOS DE CHINA NO ESPECIFICADOS": 413,
    "OTROS PUERTOS DE COREA DEL NORTE NO ESPECIFICADOS": 420,
    "NAMPO": 421,
    "BUSAN": 422,
    "OTROS PUERTOS DE COREA DEL SUR NO ESPECIFICADOS": 423,
    "MANILA": 431,
    "OTROS PUERTOS DE FILIPINAS NO ESPECIFICADOS": 432,
    "OTROS PUERTOS DE JAPON NO ESPECIFICADOS": 441,
    "OSAKA": 442,
    "KOBE": 443,
    "YOKOHAMA": 444,
    "NAGOYA": 445,
    "SHIMIZUI": 446,
    "MOJI": 447,
    "YAWATA": 448,
    "FUKUYAMA": 449,
    "KAOHSIUNG": 451,
    "KEELUNG": 452,
    "OTROS PUERTOS DE TAIWAN NO ESPECIFICADOS": 453,
    "KARHG ISLAND": 461,
    "OTROS PUERTOS DE IRAN NO ESPECIFICADOS": 462,
    "CALCUTA": 471,
    "OTROS PUERTOS DE INDIA NO ESPECIFICADOS": 472,
    "CHALNA": 481,
    "OTROS PUERTOS DE BANGLADESH NO ESPECIFICADOS": 482,
    "OTROS PUERTOS DE SINGAPUR NO ESPECIFICADOS": 491,
    "HONG KONG": 492,
    "OTROS PUERTOS ASIATICOS NO ESPECIFICADOS": 499,
    "CONSTANZA": 511,
    "OTROS PUERTOS DE RUMANIA NO ESPECIFICADOS": 512,
    "VARNA": 521,
    "OTROS PUERTOS DE BULGARIA NO ESPECIFICADOS": 522,
    "BELGRADO": 533,
    "OTROS PUERTOS DE SERBIA NO ESPECIFICADOS": 534,
    "PODGORITSA": 535,
    "OTROS PUERTOS DE MONTENEGRO NO ESPECIFICADOS": 536,
    "OTROS PUERTOS DE ITALIA NO ESPECIFICADOS": 541,
    "GENOVA": 542,
    "LIORNA, LIVORNO": 543,
    "NAPOLES": 544,
    "SALERNO": 545,
    "AUGUSTA": 546,
    "SAVONA": 547,
    "OTROS PUERTOS DE FRANCIA NO ESPECIFICADOS": 551,
    "LA PALLICE": 552,
    "LE HAVRE": 553,
    "MARSELLA": 554,
    "BURDEOS": 555,
    "CALAIS": 556,
    "BREST": 557,
    "RUAN": 558,
    "OTROS PUERTOS DE ESPANA NO ESPECIFICADOS": 561,
    "CADIZ": 562,
    "BARCELONA": 563,
    "BILBAO": 564,
    "HUELVA": 565,
    "SEVILLA": 566,
    "TARRAGONA": 567,
    "ALGECIRAS": 568,
    "VALENCIA": 569,
    "LIVERPOOL": 571,
    "LONDRES": 572,
    "ROCHESTER": 573,
    "ETEN SALVERRY": 574,
    "OTROS PUERTOS DE INGLATERRA NO ESPECIFICADOS": 576,
    "DOVER": 577,
    "PLYMOUTH": 578,
    "HELSINSKI": 581,
    "OTROS PUERTOS DE FINLANDIA NO ESPECIFICADOS": 582,
    "HANKO": 583,
    "KEMI": 584,
    "KOKKOLA": 585,
    "KOTKA": 586,
    "OULO": 587,
    "PIETARSAARI": 588,
    "PORI": 589,
    "BREMEN": 591,
    "HAMBURGO": 592,
    "NUREMBERG": 593,
    "FRANKFURT": 594,
    "DUSSELDORF": 595,
    "OTROS PUERTOS DE ALEMANIA NO ESPECIFICADOS": 596,
    "CUXHAVEN": 597,
    "ROSTOCK": 598,
    "OLDENBURG": 599,
    "AMBERES": 601,
    "OTROS PUERTOS DE BELGICA NO ESPECIFICADOS": 602,
    "ZEEBRUGGE": 603,
    "GHENT": 604,
    "OOSTENDE": 605,
    "LISBOA": 611,
    "OTROS PUERTOS DE PORTUGAL NO ESPECIFICADOS": 612,
    "SETUBAL": 613,
    "AMSTERDAM": 621,
    "ROTTERDAM": 622,
    "OTROS PUERTOS DE PAISES BAJOS NO ESPECIFICADOS": 623,
    "GOTEMBURGO": 631,
    "OTROS PUERTOS DE SUECIA NO ESPECIFICADOS": 632,
    "MALMO": 633,
    "HELSIMBORG": 634,
    "KALMAR": 635,
    "AARHUS": 641,
    "COPENHAGEN": 642,
    "OTROS PUERTOS DE DINAMARCA NO ESPECIFICADOS": 643,
    "AALBORG": 644,
    "ODENSE": 645,
    "OSLO": 651,
    "OTROS PUERTOS DE NORUEGA NO ESPECIFICADOS": 652,
    "STAVANGER": 653,
    "OTROS PUERTOS DE EUROPA NO ESPECIFICADOS": 699,
    "DURBAM": 711,
    "CIUDAD DEL CABO": 712,
    "OTROS PUERTOS DE SUDAFRICA NO ESPECIFICADOS": 713,
    "SALDANHA": 714,
    "PORT-ELIZABETH": 715,
    "MOSSEL-BAY": 716,
    "EAST-LONDON": 717,
    "OTROS PUERTOS DE AFRICA NO ESPECIFICADOS": 799,
    "SIDNEY": 811,
    "FREMANTLE": 812,
    "OTROS PUERTOS DE AUSTRALIA NO ESPECIFICADOS": 813,
    "ADELAIDA": 814,
    "DARWIN": 815,
    "GERALDTON": 816,
    "PUERTO CABO FROWARD": 817,
    "MUELLE HUACHIPATO": 818,
    "TERMINAL MARITIMO ESCUADRON": 819,
    "TERMINAL PORTUARIO TERQUIM": 820,
    "TERMINAL MUELLE MECANIZADO ESPERANZA": 821,
    "TERMINAL MARITIMO ENAEX": 822,
    "TERMINAL MARITIMO OXIQUIM": 823,
    "PASO BUTA MALLIN": 824,
    "AERODROMO LA ARAUCANIA": 825,
    "ESTACION DE MEDICION RECINTO": 826,
    "TERMINAL GRANELES DEL NORTE": 827,
    "MUELLE INTERACID TRADING (CHILE) S.A.": 828,
    "TERMINAL MARITIMO ABASTIBLE": 829,
    "TERMINAL MARITIMO ENAP": 830,
    "AERODROMO PICHOY": 831,
    "OTROS PUERTOS DE OCEANIA NO ESPECIFICADOS": 899,
    "COMBUSTIBLES Y LUBRICANTES DESTINADOS AL CONSUMO DE NAVES Y AERONAVES DE TRANSPORTE INTERNACIONAL": 900,
    "RANCHO DE NAVES Y AERONAVES DE TRANSPORTE INTERNACIONAL": 900,
    "ARICA": 901,
    "IQUIQUE": 902,
    "ANTOFAGASTA": 903,
    "COQUIMBO": 904,
    "VALPARAISO": 905,
    "SAN ANTONIO": 906,
    "TALCAHUANO": 907,
    "SAN VICENTE": 908,
    "LIRQUEN": 909,
    "PUERTO MONTT": 910,
    "CHACABUCO PUERTO AYSEN": 911,
    "PUNTA ARENAS": 912,
    "PATILLOS": 913,
    "TOCOPILLA": 914,
    "MEJILLONES": 915,
    "TALTAL": 916,
    "CHANARAL BARQUITO": 917,
    "CALDERA": 918,
    "CALDERILLA": 919,
    "HUASCO GUACOLDA": 920,
    "QUINTERO": 921,
    "JUAN FERNANDEZ": 922,
    "CONSTITUCION": 923,
    "TOME": 924,
    "PENCO": 925,
    "CORONEL": 926,
    "LOTA": 927,
    "LEBU": 928,
    "ISLA DE PASCUA": 929,
    "CORRAL": 930,
    "ANCUD": 931,
    "CASTRO": 932,
    "QUELLON": 933,
    "CHAITEN": 934,
    "TORTEL": 935,
    "NATALES": 936,
    "GUARELLO": 937,
    "PUERTO ANDINO": 938,
    "PERCY": 939,
    "CLARENCIA": 940,
    "GREGORIO": 941,
    "CABO NEGRO": 942,
    "PUERTO WILLIAMS": 943,
    "TERRITORIO ANTARTICO CHILENO": 944,
    "AEROPUERTO CARRIEL SUR": 945,
    "GUAYACAN": 946,
    "PASO PEHUENCHE": 947,
    "VENTANAS": 948,
    "PINO HACHADO (LIUCURA)": 949,
    "CALETA COLOSO": 950,
    "AGUAS NEGRAS": 951,
    "ZONA FRANCA IQUIQUE": 952,
    "ZONA FRANCA PUNTA ARENAS": 953,
    "RIO MAYER": 954,
    "RIO MOSCO": 955,
    "VISVIRI": 956,
    "CHACALLUTA": 957,
    "CHUNGARA": 958,
    "COLCHANE": 959,
    "ABRA DE NAPA": 960,
    "OLLAGUE": 961,
    "SAN PEDRO DE ATACAMA": 962,
    "SOCOMPA": 963,
    "SAN FRANCISCO": 964,
    "LOS LIBERTADORES": 965,
    "MAHUIL MALAL": 966,
    "CARDENAL SAMORE": 967,
    "PEREZ ROSALES": 968,
    "FUTALEUFU": 969,
    "PALENA CARRENLEUFU": 970,
    "PANGUIPULLI": 971,
    "HUAHUM": 972,
    "LAGO VERDE": 973,
    "APPELEG": 974,
    "PAMPA ALTA": 975,
    "HUEMULES": 976,
    "CHILE CHICO": 977,
    "BAKER": 978,
    "DOROTEA": 979,
    "CASAS VIEJAS": 980,
    "MONTE AYMOND": 981,
    "SAN SEBASTIAN": 982,
    "COYHAIQUE ALTO": 983,
    "TRIANA": 984,
    "IBANEZ PALAVICINI": 985,
    "VILLA O'HIGGINS": 986,
    "AEROP. CHACALLUTA": 987,
    "AEROP. DIEGO ARACENA": 988,
    "AEROP. CERRO MORENO": 989,
    "AEROP. EL TEPUAL": 990,
    "AEROP. C.I. DEL CAMPO": 991,
    "AEROP. A.M. BENITEZ": 992,
    "AERODROMO EL LOA": 993,
    "ARICA-TACNA": 994,
    "ARICA-LA PAZ": 995,
    "OTROS PUERTOS CHILENOS": 997,
    "PASO JAMA": 998,
    "GNL MEJILLONES": 999,
}

# Vias de transporte (Anexo 51-13)
TRANSPORT_ROUTES: dict[str, int] = {
    "MARITIMA, FLUVIAL Y LACUSTRE": 1,
    "AEREO": 4,
    "POSTAL": 5,
    "FERROVIARIO": 6,
    "CARRETERO / TERRESTRE": 7,
    "OLEODUCTOS, GASODUCTOS": 8,
    "TENDIDO ELECTRICO (Aereo, Subterraneo)": 9,
    "OTRA": 10,
    "COURIER/AEREO": 11,
}

# Clausulas de compraventa (Anexo 51-21)
SALE_CLAUSES: dict[str, int] = {
    "CIF": 1,
    "CFR": 2,
    "EXW": 3,
    "FAS": 4,
    "FOB": 5,
    "S/CL": 6,
    "FCA": 7,
    "OTRA": 8,
    "DDP": 9,
}

# Unidades de medida (Anexo 51-24)
MEASURE_UNITS: dict[str, int] = {
    "TMB": 1,
    "QMB": 2,
    "MKWH": 3,
    "TMN": 4,
    "KLT": 5,
    "KN": 6,
    "GR": 7,
    "HL": 8,
    "LT": 9,
    "U": 10,
    "DOC": 11,
    "CEN": 12,
    "MU": 13,
    "MT": 14,
    "MT2": 15,
    "MT3": 16,
    "PAR": 17,
    "KNFC": 18,
    "CARTON": 19,
    "KWH": 20,
    "KL": 21,
    "GAL": 22,
    "BAR": 23,
    "M2/1 MM": 24,
    "LB": 25,
    "GSA": 26,
    "RMA": 27,
    "YD": 28,
    "PIE": 29,
    "P3": 30,
    "PUL": 31,
    "QMN": 32,
    "SET": 33,
    "P2": 34,
    "BR": 35,
    "KB": 36,
    "U(JGO)": 37,
}

# Tipos de bulto (Anexo 51-23)
PACKAGE_TYPES: dict[str, int] = {
    "GRANEL SOLIDO, PARTICULAS FINAS (POLVO)": 1,
    "GRANEL SOLIDO, PARTICULAS GRANULARES (GRANOS)": 2,
    "GRANEL SOLIDO, PARTICULAS GRANDES (NODULOS)": 3,
    "GRANEL LIQUIDO": 4,
    "GRANEL GASEOSO": 5,
    "PIEZAS": 10,
    "TUBOS": 11,
    "CILINDRO": 12,
    "ROLLOS": 13,
    "BARRAS": 16,
    "LINGOTES": 17,
    "TRONCOS": 18,
    "BLOQUE": 19,
    "ROLLIZO": 20,
    "CAJON": 21,
    "CAJAS DE CARTON": 22,
    "FARDO": 23,
    "BAUL": 24,
    "COFRE": 25,
    "ARMAZON": 26,
    "BANDEJA": 27,
    "CAJAS DE MADERA": 28,
    "CAJAS DE LATA": 29,
    "BOTELLA DE GAS": 31,
    "BOTELLA": 32,
    "JAULAS": 33,
    "BIDON": 34,
    "JABAS": 35,
    "CESTAS": 36,
    "BARRILETE": 37,
    "TONEL": 38,
    "PIPAS": 39,
    "CAJAS NO ESPECIFICADAS": 40,
    "JARRO": 41,
    "FRASCO": 42,
    "DAMAJUANA": 43,
    "BARRIL": 44,
    "TAMBOR": 45,
    "CUNETES": 46,
    "TARROS": 47,
    "CUBO": 51,
    "PAQUETE": 61,
    "SACOS": 62,
    "MALETA": 63,
    "BOLSA": 64,
    "BALA": 65,
    "RED": 66,
    "SOBRES": 67,
    "CONTENEDOR DE 20 PIES DRY": 73,
    "CONTENEDOR DE 40 PIES DRY": 74,
    "CONTENEDOR REFRIGERADO 20 PIES": 75,
    "CONTENEDOR REFRIGERADO 40 PIES": 76,
    "ESTANQUE (no utilizar para contenedor Tank)": 77,
    "CONTENEDOR NO ESPECIFICADO (Open Top, Tank, Flat Rack, otros)": 78,
    "PALLETS": 80,
    "TABLERO": 81,
    "LAMINAS": 82,
    "CARRETE": 83,
    "AUTOMOTOR": 85,
    "ATAUD": 86,
    "MAQUINARIA": 88,
    "PLANCHAS": 89,
    "ATADOS": 90,
    "BOBINA": 91,
    "OTROS BULTOS NO ESPECIFICADOS": 93,
    "NO EXISTE BULTO": 98,
    "SIN EMBALAR": 99,
}

# Modalidades de venta (Anexo 51-26)
SALE_MODES: dict[str, int] = {
    "A FIRME": 1,
    "BAJO CONDICION": 2,
    "EN CONSIGNACION LIBRE": 3,
    "EN CONSIGNACION CON UN MINIMO A FIRME": 4,
    "SIN PAGO": 9,
}

# Formas de pago de exportacion
PAYMENT_MODES: dict[str, int] = {
    "COB1": 1,
    "COBRANZA": 2,
    "ACRED": 11,
    "CBOF": 12,
    "S/PAGO": 21,
    "ANTICIPO": 32,
}


def _key(text: str) -> str:
    """Normaliza para comparar: sin tildes, sin espacios extra, en mayúsculas."""
    stripped = unicodedata.normalize("NFKD", text)
    ascii_only = "".join(c for c in stripped if not unicodedata.combining(c))
    return " ".join(ascii_only.upper().split())


def code_for(table: dict[str, int], name: str) -> int:
    """Busca el código de name en table, tolerando tildes y mayúsculas.

    Si no lo encuentra lanza KeyError sugiriendo alternativas parecidas: es
    preferible fallar al armar el documento que mandarle al SII un código
    inventado, que pasaría el XSD y sería rechazado después.
    """
    target = _key(name)
    for label, code in table.items():
        if _key(label) == target:
            return code
    similar = [label for label in table if target in _key(label) or _key(label) in target]
    hint = f" ¿Quisiste decir {similar[:5]}?" if similar else ""
    raise KeyError(f"No hay código de Aduana para {name!r}.{hint}")
